import type { TrackContent } from './types'

/**
 * Front-End Web Development, from the published syllabus (docs/curriculum/tracks/front-end-web-development.md).
 * Module summaries are the plain-language lines from the design canvas (PrismTrack).
 * A test keeps the modules, lessons, projects and outcomes identical to the syllabus, so change both together.
 */
export const frontEnd: TrackContent = {
  slug: 'front-end-web-development',
  title: 'Front-End Web Development',
  status: 'live',
  tone: 'fe',
  tagline: 'Build websites that work on every screen',
  summary: 'Build responsive, accessible, interactive websites from scratch, and ship them to the web.',
  level: 'Beginner',
  audience: 'Complete beginners, including career switchers and students',
  prerequisites: 'Basic computer and phone use. No coding experience needed.',
  hours: 140,
  pace: 'About 6–7 months at 5 hours a week',
  tools: [
    'HTML',
    'CSS',
    'JavaScript',
    'VS Code',
    'The terminal',
    'DevTools',
    'Git',
    'GitHub',
    'GitHub Pages',
    'npm',
    'Vite',
    'Prettier',
    'ESLint',
    'REST APIs',
    'EmailJS',
    'Netlify',
    'Figma',
  ],
  alignment: [
    'MDN Curriculum: both getting-started modules, all 9 core modules, and six extensions',
    'WCAG 2.2 AA',
    'SFIA 9: PROG levels 2–3, HCEV 2, ACIN 2, TEST 2, RELM 2',
  ],
  credential: 'PractiCode Learn Certificate: Front-End Web Development (Open Badges 3.0)',
  deviceNotes: [
    'Modules 1 and 2, and every lesson’s predict, investigate and review steps, work on a phone.',
    'Module 3 sets up VS Code and the terminal on a computer. Phone learners can practise the same commands in the terminal and Git simulator, and the module lists free cloud editors.',
    'From Module 4, writing larger amounts of code is much easier on a laptop, and we recommend one.',
  ],
  outcomes: [
    'Build semantic, accessible web pages that meet WCAG 2.2 AA.',
    'Lay out responsive interfaces with Flexbox and Grid that work from 320 px phones to wide desktops.',
    'Write JavaScript that responds to users and fetches live data from REST APIs.',
    'Use the terminal, Git and GitHub to version, collaborate on and publish code.',
    'Set up a modern project with npm, Vite, Prettier and ESLint.',
    'Test, optimise and deploy a site to production, on your own domain.',
    "Use AI assistants critically: ask good questions, check the answers and never ship code you can't explain.",
    'Present a portfolio of at least six projects hosted under your own name.',
  ],
  capstone: {
    title: 'Capstone',
    summary: 'Plan, build and ship a multi-page site from a real-world brief.',
    project: 'A portfolio site, plus a site for a real local business or non-profit',
  },
  modules: [
    {
      number: 1,
      title: 'How the web works',
      summary: 'What really happens between tapping a link and seeing a page.',
      mdn: 'Core: Web standards and semantics',
      project: 'An "About me" page, built in the browser',
      free: true,
      lessons: [
        { title: 'What happens when you open a website' },
        { title: 'URLs, domains and DNS' },
        { title: 'Requests, responses and status codes' },
        { title: 'HTML, CSS and JavaScript: who does what' },
        { title: 'Your first web page' },
        { title: "Reading MDN, the developer's dictionary" },
      ],
    },
    {
      number: 2,
      title: 'HTML: structure and meaning',
      summary: 'Structure content so browsers, search engines and screen readers all understand it.',
      mdn: 'Core: Semantic HTML',
      project: 'A menu page for a local restaurant',
      free: false,
      lessons: [
        { title: 'Elements, tags and attributes' },
        { title: 'Headings, paragraphs and lists' },
        { title: 'Links and file paths' },
        { title: 'Images and alt text' },
        { title: 'Page structure: header, nav, main, footer' },
        { title: 'Sections and articles' },
        { title: 'Tables, used properly' },
        { title: 'Forms: inputs, labels and buttons' },
        { title: 'Built-in form validation' },
        { title: 'The head: titles, meta tags and link previews' },
      ],
    },
    {
      number: 3,
      title: 'Your toolkit and your first live site',
      summary: 'VS Code, the terminal, Git and GitHub, then put your first site live.',
      mdn: 'Getting started: Environment setup, Soft skills · Core: Version control',
      project: 'The menu page, live on the web, with a README',
      free: false,
      lessons: [
        { title: 'Files, folders and paths' },
        { title: 'Setting up VS Code' },
        { title: 'No laptop yet? Free cloud editors' },
        { title: 'The terminal in 15 minutes' },
        { title: 'Git basics: init, add, commit' },
        { title: 'GitHub: push your code' },
        { title: 'Publish with GitHub Pages' },
        { title: 'Browser DevTools' },
        { title: 'AI assistants: ask, check, understand' },
      ],
    },
    {
      number: 4,
      title: 'CSS fundamentals',
      summary: 'Selectors, the cascade and the box model, and how to debug them in DevTools.',
      mdn: 'Core: CSS fundamentals',
      project: 'Style the restaurant menu',
      free: false,
      lessons: [
        { title: 'Connecting CSS to HTML' },
        { title: 'Selectors' },
        { title: 'The cascade and specificity' },
        { title: 'Inheritance' },
        { title: 'Colour and contrast' },
        { title: 'Units: px, rem, %, vw' },
        { title: 'The box model' },
        { title: 'Block and inline' },
        { title: 'Custom properties' },
        { title: 'Debugging CSS in DevTools' },
      ],
    },
    {
      number: 5,
      title: 'Typography, images and icons',
      summary: 'Readable type, fast web fonts, responsive images and SVG icons.',
      mdn: 'Core: CSS text styling',
      project: 'A magazine-style article page',
      free: false,
      lessons: [
        { title: 'Web fonts that load fast' },
        { title: 'Type scales and readable text' },
        { title: 'Spacing systems' },
        { title: 'Responsive images and modern formats' },
        { title: 'SVG icons' },
        { title: 'Backgrounds, borders and shadows' },
      ],
    },
    {
      number: 6,
      title: 'Flexbox',
      summary: 'Line things up in a row or a column, then spread them out or centre them.',
      mdn: 'Core: CSS layout',
      project: 'A navigation bar and card section',
      free: false,
      lessons: [
        { title: 'Normal flow' },
        { title: 'Flex containers, main and cross axis' },
        { title: 'justify-content' },
        { title: 'Aligning items with Flexbox' },
        { title: 'Wrapping and gap' },
        { title: 'grow, shrink and basis' },
        { title: 'Patterns: navbars, cards, footers, centring' },
      ],
    },
    {
      number: 7,
      title: 'Grid and responsive design',
      summary: 'Two-dimensional layouts that adapt from small phones to wide screens.',
      mdn: 'Core: CSS layout · Extension: Transform and animate CSS',
      project: 'A responsive landing page for a local business',
      free: false,
      lessons: [
        { title: 'Rows, columns and fr' },
        { title: 'Placing items and naming areas' },
        { title: 'auto-fit and minmax' },
        { title: 'Mobile-first and media queries' },
        { title: 'Container queries' },
        { title: 'Positioning and z-index' },
        { title: 'Transitions, animation and reduced motion' },
        { title: 'Testing on real phones' },
      ],
    },
    {
      number: 8,
      title: 'JavaScript fundamentals',
      summary: 'Variables, functions, loops, arrays and objects, and how to debug them.',
      mdn: 'Core: JavaScript fundamentals',
      project: 'A bill splitter',
      free: false,
      lessons: [
        { title: 'What JavaScript does, and the console' },
        { title: 'let and const' },
        { title: 'Strings, numbers and booleans' },
        { title: 'Comparisons and conditions' },
        { title: 'Functions' },
        { title: 'Arrays' },
        { title: 'Loops' },
        { title: 'Objects' },
        { title: 'Template literals and string methods' },
        { title: 'Debugging with breakpoints' },
      ],
    },
    {
      number: 9,
      title: 'Thinking in JavaScript',
      summary: 'Break problems into steps, and use array methods, errors and modules.',
      mdn: 'Core: JavaScript fundamentals',
      project: "A budget tracker's logic, with tests",
      free: false,
      lessons: [
        { title: 'Breaking problems into steps' },
        { title: 'Scope' },
        { title: 'map, filter and find' },
        { title: 'reduce' },
        { title: 'Errors and try…catch' },
        { title: 'Modules: import and export' },
        { title: "Reading other people's code" },
      ],
    },
    {
      number: 10,
      title: 'The DOM and events',
      summary: 'Make pages respond to taps, typing and forms.',
      mdn: 'Extension: Web APIs',
      project: 'An interactive quiz',
      free: false,
      lessons: [
        { title: 'What the DOM is' },
        { title: 'Selecting elements' },
        { title: 'Changing text, classes and attributes' },
        { title: 'Creating and removing elements' },
        { title: 'Click, input and submit events' },
        { title: 'Event delegation' },
        { title: 'Form validation with JavaScript' },
        { title: 'Saving data with localStorage' },
        { title: 'Focus and keyboard support' },
      ],
    },
    {
      number: 11,
      title: 'Data and APIs: fetch, JSON and EmailJS',
      summary: 'Pull live data into your pages, handle slow and broken cases, and send a form.',
      mdn: 'Extensions: Web APIs, Security and privacy',
      project: 'A currency or weather dashboard with a working contact form',
      free: false,
      lessons: [
        { title: 'JSON' },
        { title: 'How APIs work' },
        { title: 'Promises and async/await' },
        { title: 'Fetching data' },
        { title: 'Loading, empty and error states' },
        { title: 'Sending data with POST' },
        { title: 'Contact forms with EmailJS' },
        { title: "API keys: what's safe in front-end code" },
        { title: 'Debugging network requests' },
      ],
    },
    {
      number: 12,
      title: 'Git for teams and modern tooling',
      summary: 'Branches and pull requests, then npm, Vite, Prettier and ESLint.',
      mdn: 'Core: Version control · Extension: Modern tooling',
      project: 'Move the dashboard to Vite through a pull request',
      free: false,
      lessons: [
        { title: 'Branches' },
        { title: 'Merging and conflicts' },
        { title: 'Pull requests and code review' },
        { title: 'Good commits and .gitignore' },
        { title: 'Node and npm' },
        { title: 'package.json and scripts' },
        { title: 'Vite' },
        { title: 'Prettier and ESLint' },
        { title: 'Using a library from npm' },
      ],
    },
    {
      number: 13,
      title: 'Accessibility',
      summary: 'Audit and fix pages against WCAG 2.2 AA, with a screen reader and a keyboard.',
      mdn: 'Core: Accessibility',
      project: 'An accessibility audit and fix of an earlier project',
      free: false,
      lessons: [
        { title: 'Who accessibility is for' },
        { title: 'Keyboard and focus' },
        { title: 'Screen readers: TalkBack and NVDA' },
        { title: 'Contrast and colour' },
        { title: 'Accessible forms and errors' },
        { title: 'Automated audits: axe and Lighthouse' },
      ],
    },
    {
      number: 14,
      title: 'Design for developers',
      summary: 'Hierarchy, spacing and colour, and how to build from a Figma file.',
      mdn: 'Core: Design for developers',
      project: 'Build a page from a Figma design',
      free: false,
      lessons: [
        { title: 'Visual hierarchy' },
        { title: 'Alignment, spacing and consistency' },
        { title: 'Reading a Figma file' },
        { title: 'Exporting assets' },
        { title: 'Building a design faithfully' },
      ],
    },
    {
      number: 15,
      title: 'Ship it: performance, SEO and real clients',
      summary: 'Core Web Vitals, SEO, your own domain, and working with a client.',
      mdn: 'Extensions: Performance, Testing · Getting started: Soft skills',
      project: 'Deploy a site with a Lighthouse score of 90+',
      free: false,
      lessons: [
        { title: 'Lighthouse and Core Web Vitals' },
        { title: 'Faster images and fonts' },
        { title: 'SEO basics' },
        { title: 'Deploying to Netlify from GitHub' },
        { title: 'Custom domains and HTTPS' },
        { title: 'Netlify forms and redirects' },
        { title: 'A first automated test' },
        { title: 'Working with a client: brief, scope, handover' },
      ],
    },
  ],
}
